language: python
dist: xenial
sudo: false
python:
- '3.7'
install:
- pip install -U pip wheel setuptools
- pushd ~
- git clone --depth 1 https://github.com/pretix/pretix.git
- cd pretix/src
- pip3 install -Ur requirements.txt -r requirements/dev.txt
- python setup.py develop
- make all compress
- popd
script:
- flake8 .
- isort -c -rc .
cache:
  directories:
  - "$HOME/.cache/pip"
addons:
  apt:
    packages:
    - enchant
    - myspell-de-de
    - aspell-en
deploy:
  provider: pypi
  user: aruanoguate
  password:
    secure: x9NZ/xHlCGvqk+CnhJThG1qXmjmliUFZxcrzRGgniN7/AD0lh48e1Q0AX2cUAWRfwPZOxe17w8NMtY1nu2twkUHvPG5zHBuDYOtFbrJF0DfNH7AfXJEngYwCjDQcAVICdVWjlCqwdcwj9KOFaDC5qpfLhDagfIpwzXm4FA5AJOtF703odzeTA/EPAKZdH/PvJanLPvSt5IQk1kFGRNGenY169jhaRtc7vfKR01yAiZYIDW6vpHYerXNYQHd776bJwlCHrll/LZ54yKik0U9LD5eeK6EXjByJ5Gz7gOhnxMl4A08BpSj+FodrgHSsTLQFwNl89/ZSM6Thbk3EZia84dWZxgJQomeQpujN5p/9b9gGeapf4RtbpLY2GtRYQu0YHPOgJ1jATRjs7eBWVRVrLfJt3AE3RJmglrVQzcCaAQy2qQRJdGWsx4mTBvPSOC6MOumaKhNsz51MOgqr1DlC8gyLuwhy38E4wzC7BR+EkgdMS5Pp6ZzR8ejEcZjQ8xAdsTpzf1tubmCZx2icaNk1C+NItGhmwVQ20XtOS4b6qsjit3l0p6PZmhct2fIrilkW7inx2PJrPCXOnYnfVKzRyykrMYDjgmEFcY7F1R9Azyg6Xtpd/i0Q8qtRKwXwnCh5n9LCgkRnaVRh1IzdglYIbQ7WRLB9E/K6lgAnQ7R8Gd0=
  on:
    tags: true
